DROP TABLE IF EXISTS flyway_schema_history;
DROP TABLE IF EXISTS users_roles;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS counters;
DROP TABLE IF EXISTS cities;
DROP TABLE IF EXISTS cards;
DROP TABLE IF EXISTS documents;