DROP TABLE IF EXISTS flyway_schema_history CASCADE;
DROP TABLE IF EXISTS users_roles CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS counters CASCADE;
DROP TABLE IF EXISTS cities CASCADE;
DROP TABLE IF EXISTS cards CASCADE;
DROP TABLE IF EXISTS documents CASCADE;