server:
  port: 8080
  servlet:
    context-path: /lk_loyality

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lk_loyality
    username: gb_user
    password: gb_user
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
jwt:
  secret: myFrends123*
app:
  city: Нижний Новгород